-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 21:50:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AP2_ Engenharia_de_Dados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AP2_ Engenharia_de_Dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AP2_ Engenharia_de_Dados` DEFAULT CHARACTER SET utf8 ;
USE `AP2_ Engenharia_de_Dados` ;

-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`Musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`Musica` (
  `id` INT NOT NULL,
  `Título` VARCHAR(45) NOT NULL,
  `Letra` VARCHAR(500) NOT NULL,
  `Data_Lancamento` DATE NOT NULL,
  `Duracao_segundos` INT NOT NULL,
  `Censura` INT NOT NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`autor_musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`autor_musica` (
  `fk_autor` VARCHAR(45) NOT NULL,
  `fk_musica` INT NOT NULL,
  PRIMARY KEY (`fk_autor`, `fk_musica`),
  CONSTRAINT `fk_autor`
    FOREIGN KEY (`fk_autor`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Autor` (`Nome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_musica`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Musica` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`Autor` (
  `Nome` VARCHAR(45) NOT NULL,
  `fk_musica` INT NOT NULL,
  PRIMARY KEY (`Nome`),
  CONSTRAINT `fk_autor_musica`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`autor_musica` (`fk_musica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`compositor_musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`compositor_musica` (
  `fk_compositor` VARCHAR(45) NOT NULL,
  `fk_musica` INT NOT NULL,
  PRIMARY KEY (`fk_compositor`, `fk_musica`),
  CONSTRAINT `fk_compositor`
    FOREIGN KEY (`fk_compositor`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Compositor` (`Nome`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_muscia`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Musica` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`Compositor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`Compositor` (
  `Nome` VARCHAR(45) NOT NULL,
  `fk_musica` INT NOT NULL,
  PRIMARY KEY (`Nome`),
  CONSTRAINT `fk_compositor_musica`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`compositor_musica` (`fk_musica`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`categoria_musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`categoria_musica` (
  `fk_categoria` VARCHAR(45) NOT NULL,
  `fk_musica` INT NOT NULL,
  PRIMARY KEY (`fk_categoria`, `fk_musica`),
  CONSTRAINT `fk_categoria_musica_2`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Categoria` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musica_categoria`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Musica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`Categoria` (
  `Nome` VARCHAR(45) NOT NULL,
  `fk_musica` INT NOT NULL,
  PRIMARY KEY (`Nome`),
  CONSTRAINT `fk_categoria_musica_1`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`categoria_musica` (`fk_musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`Playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Data_criacao` DATE NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `visibildade` TINYINT NOT NULL,
  `fk_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `fk_categoria`),
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Categoria` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`Usuario` (
  `Nome` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATE NULL,
  `cpf` CHAR(11) NOT NULL,
  `numero_cartao` INT NOT NULL,
  `fk_playlist` INT NOT NULL,
  `Usuariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_playlist`
    FOREIGN KEY (`fk_playlist`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `AP2_ Engenharia_de_Dados`.`musica_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AP2_ Engenharia_de_Dados`.`musica_playlist` (
  `fk_musica` INT NOT NULL,
  `fk_playlist` INT NOT NULL,
  PRIMARY KEY (`fk_playlist`, `fk_musica`),
  CONSTRAINT `fk_musica`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Musica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist`
    FOREIGN KEY (`fk_playlist`)
    REFERENCES `AP2_ Engenharia_de_Dados`.`Playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
